name: smart_resume_analyzer
description: A cross-platform Flutter app that evaluates resumes and provides major-specific feedback.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2

  permission_handler: ^12.0.0+1

  google_fonts: ^6.2.1

  # State management
  provider: ^6.1.1

  # File selection and PDF parsing
  file_picker: ^10.1.2
  syncfusion_flutter_pdf: ^29.1.38

  # HTTP for networking (used in online analysis mode)
  http: ^1.3.0

  # Optional: rendering the resume as a blurred PDF in the background
  flutter_pdfview: ^1.2.0

  # Core Flutter packages
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
